#!/bin/bash
##:: ***** DO NOT EDIT THIS FILE.  READ THIS FIRST. *****
##::
##:: Any changes you make to this file may get commited and will be visible
##:: to other developers.
##::
##:: So if you want to customize your build environment, create a copy first
##:: (say mysetenv.sh) and then edit the copy only.


echo Setting env
export PROJ_HOME=$PWD

export PROJ_JDK_HOME=~/jdk1.6.0_23
export PROJ_ANT_HOME=../../dev-tools/apache-ant-1.7.1

#::
#:: Initalize PATH and other stuff
#::

export PATH=$PROJ_JDK_HOME/bin:$PATH
export JAVA_HOME=$PROJ_JDK_HOME
export PATH=$PROJ_ANT_HOME/bin:$PATH

echo Environment Initialized:
echo PROJ_HOME=$PROJ_HOME
echo PROJ_JDK_HOME=$PROJ_JDK_HOME
echo PROJ_ANT_HOME=$PROJ_ANT_HOME
